### ISSUE TITLE
Suggest using Git-flow

### ISSUE THREAD

**Issue by yjnoh1016** [Tita-dev/Tita-Android#3]
현재 layout 작업 시 바로 `master branch`로 `push`하는 방식을 사용 중인 것으로 보입니다.
단순한 프로젝트가 아닌 계속 유지보수를 해나갈 서비스이기 때문에 서비스를 위해서 **Git-flow** 방식을 도입하는 것을 제안드립니다!
이 방식으로 협업을 진행하며  `Code-review`까지 활성화 시키는 것이 좋을 것 같습니다🤔
조금 더 원활한 개발을 위해 적극 반영 부탁드립니다!

여기 Git-flow 이해를 돕는 자료입니다.
https://woowabros.github.io/experience/2017/10/30/baemin-mobile-git-branch-strategy.html

**Comment by GSMYunsung** [comment]
저희의 방식을 지적해주셔서 감사합니다! 빠른시일내에 반영해보겠습니다
