### ISSUE TITLE
current structure

### ISSUE THREAD

**Issue by GSMYunsung** [Tita-dev/Tita-Android#4]
현재 안드로이드 구조를 보면 Base 라는 클래스가있는데 베이스에 대한 설명이 부족한거 같습니다. 
Base 에서 정확히 어떤 일을 해주고있는지 자세한 설명 부탁드리겠습니다.

**Comment by ckrudals** [comment]
Base 란 dataBinding 을 사용할 때 activity, fragment, viewModel 에 똑같은 코드를 구현해야하는데 중복 코드를 제거하기 위해 base패키지를 만들어 관리하여 편의를 준다는 장점이 있습니다.
